export const metadata = {
  title: 'Privacy Policy — Campus Market',
  description: 'Privacy Policy for Campus Market, compliant with the Zambia Data Protection Act, 2021.',
};

function Section({ number, title, children }) {
  return (
    <section className="border-t border-border pt-6 mt-6 first:border-t-0 first:pt-0 first:mt-0">
      <h2 className="text-xl font-bold tracking-tight text-foreground">
        {number}. {title}
      </h2>
      <div className="mt-3 space-y-3 text-muted-foreground leading-relaxed">
        {children}
      </div>
    </section>
  );
}

const dataTable = [
  { category: 'Account data', examples: 'Name, email or phone number, institution/school, password (hashed)', source: 'Provided by you at registration' },
  { category: 'Profile data', examples: 'Display name, avatar, tier, role', source: 'Provided by you' },
  { category: 'Listing data', examples: 'Title, description, price, images, category', source: 'Provided by you' },
  { category: 'Communications', examples: 'In-app chat messages between users', source: 'Generated by you when using chat' },
  { category: 'Usage data', examples: 'Login times, device/browser type, IP address, pages viewed', source: 'Automatically collected' },
  { category: 'Transaction signals', examples: 'Fraud/moderation flags on listings', source: 'Generated by our automated checks' },
];

export default function PoliciesPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <div className="rounded-3xl border border-border bg-card p-6 sm:p-10 shadow-sm">
        <div className="mb-8">
          <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
            Legal
          </div>
          <h1 className="mt-4 text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-muted-foreground">Campus Market — Last updated: July 2026</p>
        </div>

        <p className="text-muted-foreground leading-relaxed">
          This Privacy Policy explains how Campus Market (&ldquo;we,&rdquo; &ldquo;us&rdquo;) collects, uses,
          stores, and protects your personal data, in accordance with the{' '}
          <strong>Data Protection Act No. 3 of 2021</strong> of the Republic of Zambia, and in conjunction with the
          Cyber Security and Cyber Crimes Act No. 2 of 2021 and the Electronic Communications and Transactions Act
          No. 4 of 2021.
        </p>

        <Section number={1} title="Who We Are">
          <p>
            Campus Market is the <strong>data controller</strong> responsible for personal data processed through
            the Platform. [Insert registered business name / entity if applicable.]
          </p>
        </Section>

        <Section number={2} title="What Data We Collect">
          <div className="overflow-x-auto rounded-xl border border-border">
            <table className="w-full text-sm text-left">
              <thead className="bg-muted/50 text-foreground">
                <tr>
                  <th className="px-4 py-2 font-semibold">Category</th>
                  <th className="px-4 py-2 font-semibold">Examples</th>
                  <th className="px-4 py-2 font-semibold">Source</th>
                </tr>
              </thead>
              <tbody>
                {dataTable.map((row) => (
                  <tr key={row.category} className="border-t border-border">
                    <td className="px-4 py-2 font-medium text-foreground align-top">{row.category}</td>
                    <td className="px-4 py-2 align-top">{row.examples}</td>
                    <td className="px-4 py-2 align-top">{row.source}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p>
            We do not knowingly collect sensitive personal data (e.g. health, religion, biometric data) unless you
            voluntarily include it in a listing or message, which we discourage.
          </p>
        </Section>

        <Section number={3} title="Why We Collect It (Lawful Basis)">
          <p>
            Consistent with the Data Protection Act&rsquo;s requirement that data be collected only for specific,
            lawful purposes and kept to what is necessary, we process your data to:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Create and secure your account (contract necessity)</li>
            <li>Display your listings to other users on the Platform (contract necessity)</li>
            <li>Enable in-app chat between buyers and sellers (contract necessity)</li>
            <li>Run automated fraud and abuse detection (legitimate interest — platform safety)</li>
            <li>Send you service-related notifications (contract necessity / consent for marketing)</li>
            <li>Comply with lawful requests from Zambian authorities (legal obligation)</li>
          </ul>
        </Section>

        <Section number={4} title="How We Use Your Data">
          <ul className="list-disc pl-5 space-y-2">
            <li>To operate core features: posting/browsing listings, messaging, following sellers, and the recommendation/feed ranking system.</li>
            <li>
              To detect fraud: our system flags listings with, for example, prices far below category median, very
              new accounts, or contact details posted to route around in-app chat. Flags are reviewed manually — we
              do not auto-delete listings based on automated flags alone.
            </li>
            <li>To improve the Platform, in aggregate/anonymized form where possible.</li>
          </ul>
          <p>We do <strong>not</strong> sell your personal data to third parties.</p>
        </Section>

        <Section number={5} title="Where Your Data Is Stored">
          <p>
            Your data is stored using Supabase (Postgres database, Auth, and Storage) and cached in Upstash Redis.
            [Insert actual hosting region(s) — e.g. if your Supabase project or Redis instance is hosted outside
            Zambia, disclose this explicitly here.]
          </p>
          <p>Where personal data is transferred or stored outside Zambia, we do so only where:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>the receiving country/provider maintains an adequate level of data protection, or</li>
            <li>you have given consent to the transfer, or</li>
            <li>the transfer is otherwise permitted under the Data Protection Act, 2021.</li>
          </ul>
          <p>
            Sensitive personal data (if any is ever collected) will not be transferred outside Zambia without your
            explicit consent.
          </p>
        </Section>

        <Section number={6} title="Data Retention">
          <p>
            We keep your personal data only for as long as necessary for the purpose it was collected, and, in line
            with the Data Protection Act&rsquo;s minimum standard, for{' '}
            <strong>no less than one year after that purpose ends</strong>, unless a longer period is required by
            law (e.g. fraud investigation records) or you request earlier deletion where legally permitted.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Account data: retained while your account is active, plus a retention period after closure for legal/fraud purposes.</li>
            <li>Chat messages: retained to support moderation and dispute resolution.</li>
            <li>Deleted listings: soft-deleted and retained briefly before permanent removal.</li>
          </ul>
        </Section>

        <Section number={7} title="Your Rights">
          <p>Under the Data Protection Act, 2021, you have the right to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Confirm</strong> whether we are processing your personal data</li>
            <li><strong>Access</strong> the personal data we hold about you and information about how it&rsquo;s processed</li>
            <li><strong>Correct</strong> inaccurate or outdated personal data</li>
            <li><strong>Request deletion</strong> of your personal data, subject to legal retention requirements</li>
            <li><strong>Object</strong> to certain processing, including for direct marketing</li>
            <li><strong>Withdraw consent</strong> at any time, where processing is based on consent</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:privacy@campusmarket.example" className="text-primary hover:underline">
              privacy@campusmarket.example
            </a>
            . We will respond within the timeframe required by law.
          </p>
          <p>
            If you believe your data has been mishandled, you may also lodge a complaint with the{' '}
            <strong>Office of the Data Protection Commissioner</strong> in Zambia.
          </p>
        </Section>

        <Section number={8} title="Data Security">
          <p>
            We apply safeguards consistent with the Cyber Security and Cyber Crimes Act, 2021 and general good
            practice, including:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Row Level Security (RLS) on our database, restricting each user&rsquo;s access to only their own data</li>
            <li>JWT-based authentication verified on every request</li>
            <li>Rate limiting to reduce automated abuse</li>
            <li>Server-side validation of file type and size before accepting image uploads</li>
            <li>Encryption in transit (HTTPS/WSS) for all client-server communication</li>
          </ul>
          <p>
            No system is 100% secure. In the event of a data breach affecting your personal data, we will notify
            the Data Protection Commissioner and affected users as required under the Data Protection Act, 2021.
          </p>
        </Section>

        <Section number={9} title="Cookies & Similar Technologies">
          <p>
            We use session cookies/tokens necessary for authentication and basic functionality. [Add detail here if
            you introduce analytics or marketing cookies — these require additional consent under the Act.]
          </p>
        </Section>

        <Section number={10} title="Children's Data">
          <p>
            Campus Market is intended for users affiliated with participating institutions who are 18 or older, or
            younger users using the Platform with parental/guardian consent as required by the Cyber Security and
            Cyber Crimes Act&rsquo;s child online protection provisions. We do not knowingly collect data from
            children without appropriate consent.
          </p>
        </Section>

        <Section number={11} title="Third-Party Processors">
          <p>
            We use the following processors to operate the Platform, each acting under contractual data protection
            obligations:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Supabase</strong> — authentication, database, file storage</li>
            <li><strong>Upstash</strong> — caching and rate limiting</li>
            <li><strong>Render/Railway</strong> — application hosting</li>
            <li><strong>Vercel</strong> — frontend hosting/CDN</li>
          </ul>
        </Section>

        <Section number={12} title="Changes to This Policy">
          <p>
            We may update this Privacy Policy from time to time. Material changes will be communicated in-app or by
            email before they take effect.
          </p>
        </Section>

        <Section number={13} title="Contact Us">
          <p>
            For privacy questions, data access/deletion requests, or complaints, contact:{' '}
            <a href="mailto:privacy@campusmarket.example" className="text-primary hover:underline">
              privacy@campusmarket.example
            </a>
          </p>
          <p>
            <strong>Office of the Data Protection Commissioner (Zambia)</strong> — for complaints that cannot be
            resolved directly with us. [Insert current DPC contact details once you have them, as the office&rsquo;s
            contact information may be updated by the Zambian government from time to time.]
          </p>
        </Section>
      </div>
    </div>
  );
}